# These are supported funding model platforms

github: [seu-usuario] # Substitua com seu nome de usuário do GitHub
patreon: # Substitua com seu nome de usuário do Patreon
open_collective: # Substitua com seu nome de usuário do Open Collective
ko_fi: # Substitua com seu nome de usuário do Ko-fi
tidelift: # Substitua com seu nome de usuário do Tidelift
community_bridge: # Substitua com seu nome de usuário do Community Bridge
liberapay: # Substitua com seu nome de usuário do Liberapay
issuehunt: # Substitua com seu nome de usuário do IssueHunt
otechie: # Substitua com seu nome de usuário do Otechie
custom: # Substitua com sua URL personalizada de financiamento 